//
//  QiHiddenAdPanel.h
//  QiGames
//
//  Hidden ad panel: used for ad triggering tests by the publishing channel.
//  Trigger condition: the text field in the home view == "show**show**show".
//  Note: once the panel is shown, no toast / alert is displayed (per the spec).
//

// ---------------------------------------------------------------------------
// Hidden ad panel master switch (single source of truth).
//
//   Default = 1 (enabled):
//     IPA builds delivered to the publishing channel include the hidden panel
//     and its trigger logic for ad verification.
//
//   App Store builds MUST ship with this set to 0:
//     The panel + trigger are hidden/unlisted functionality, which App Review
//     rejects if discovered. With the switch off, the trigger logic in
//     QiDrawViewController.m and the whole QiHiddenAdPanel implementation are
//     excluded from compilation -- no code changes or deletions required.
//
//   How to turn it off for App Store packaging (do NOT edit this file):
//     * Local:  xcodebuild ... -configuration Release \
//                 -xcconfig Configs/AppStore.xcconfig ...
//     * CI:     run the "CI Package" workflow with app_store = true
//     (Configs/AppStore.xcconfig defines GCC_PREPROCESSOR_DEFINITIONS with
//     HIDDEN_AD_PANEL_ENABLED=0, which overrides this default below.)
// ---------------------------------------------------------------------------
#ifndef HIDDEN_AD_PANEL_ENABLED
#define HIDDEN_AD_PANEL_ENABLED 1
#endif

#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

/**
 *  Hidden ad panel: overlaid on the current keyWindow, providing load-status
 *  display, playback and auto-refresh for the rewarded / interstitial ad slots.
 */
@interface QiHiddenAdPanel : NSObject

/**
 *  Shows the hidden ad panel (overlaid on the current keyWindow, covering the
 *  full screen). Automatically loads all platform ads on first open.
 *
 *  @return None.
 */
+ (void)show;

/**
 *  Dismisses the hidden ad panel.
 *
 *  @return None.
 */
+ (void)dismiss;

@end

NS_ASSUME_NONNULL_END
